apiVersion: v1
kind: Service
metadata:
  labels:
    app: accounts
  name: accounts-service
spec:
  ports:
  - port: 80
    targetPort: 3000
    appProtocol: http
  selector:
    app: accounts-pod
  type: ClusterIP
