apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer
  name: customer-service
spec:
  ports:
  - port: 80
    targetPort: 3000
    appProtocol: http
  selector:
    app: customer-pod
  type: ClusterIP
